### ISSUE TITLE
运行时出现的段错误Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by 3DV-Coder** [XiaoHan-Git/RO-MAP#2]
你好，在运行环境配置完毕后，我分别尝试运行了offline和online。均出现了段错误，使用gdb定位到错误，但我没能解决它。请问您是否遇到过，或者有什么可能解决的办法？
以下是问题描述：
1） 在运行offline时段错误
![2023-05-23 16-55-52屏幕截图](https://github.com/XiaoHan-Git/RO-MAP/assets/81694025/706fe757-b998-41c3-b4ba-865599c8d396)
gdb定位错误
![2023-05-23 16-57-53屏幕截图](https://github.com/XiaoHan-Git/RO-MAP/assets/81694025/035e2f41-0525-44ea-9fb5-d0a20a8b422e)
bt跟踪错误
![2023-05-23 16-58-53屏幕截图](https://github.com/XiaoHan-Git/RO-MAP/assets/81694025/736feb8e-ed83-4526-a1b6-88e0a6fb3915)

2）在运行online时段错误
![2023-05-23 16-41-34屏幕截图](https://github.com/XiaoHan-Git/RO-MAP/assets/81694025/1fdd3ca2-a940-447d-aeb3-ecc791716639)
![2023-05-23 16-42-04屏幕截图](https://github.com/XiaoHan-Git/RO-MAP/assets/81694025/57b3db39-47a0-4d0d-bf5e-e5e8614dc8e0)
gdb定位错误
![2023-05-23 16-45-38屏幕截图](https://github.com/XiaoHan-Git/RO-MAP/assets/81694025/f74bd48b-20d7-405a-b3a2-1e99e71831ba)
bt跟踪错误
![2023-05-23 16-46-08屏幕截图](https://github.com/XiaoHan-Git/RO-MAP/assets/81694025/1163a178-6551-476e-889b-3ce19b767067)

**Comment by XiaoHan-Git** [comment]
你好，首先感谢你的关注。
对于离线版本的错误。看起来是cuda内存操作时出现的。你的GPU型号，CUDA版本是多少？
1. 请先确保所有的编译单元采用相同的编译模式，sh文件中都默认为RelWithDebInfo。
2. 尝试仅构建一个对象NeRF模型，看是否仍然报错。
./RO-MAP/dependencies/Multi-Object-NeRF/main.cpp中 327行 修改 vObjPath.size() 为 1
```c++
for(int i=0;i<vObjPath.size();i++)
    {
        nerfManager.CreateNeRF(vObjPath[i]);
    }
```
请先尽可能跑通离线版本，再尝试在线版本

**Comment by 3DV-Coder** [comment]
谢谢你提供的帮助。这个问题似乎的确和cuda有关。
最初我使用的GPU是3060ti，cuda版本是11.3。我担心是由于cuda版本导致报错。这次我换了一台新的服务器（GPU 3090），严格按照repo中要求的版本和操作重新配置环境。
* Eigen3 version: 3.3.7
* OpenCV version: 3.4.16
* Pangolin version: 0.8
* CMake version: 3.25
* CUDA version: 11.8
编译模式都采用的是RelWithDebInfo，并且按照你的第二个建议做了尝试。但是仍然出现了同样的报错。
```terminal
......Multi-Object NeRF Offline......
mNumGPU: 1
Detect 1 GPU ...
Load Images to GPU ...
Load Images to GPU completed...
GridEncoding:Nmin=16 b=1.38191 F=2 T=2^16 L=16
Model: 3--[HashGrid]-->32--[FullyFusedMLP(n_neurons=64|n_hidden_layers=1)]-->4(density=1,color=3)
 total_encoding_params=1908736 total_network_params=3072
allocate_time: 60
Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.terminate called after throwing an instance of 'std::runtime_error'
  what():  /home/zxq/MachineLearning/SLAM/RO-MAP/dependencies/Multi-Object-NeRF/Core/src/nerf_model.cu:1469 cudaStreamSynchronize(pStream) failed with error an illegal memory access was encountered
已放弃 (核心已转储)
```
gdb定位到的出错位置和之前大致相同（每次重新运行，段错误定位的位置都会出现一点差别，但大致相同）
```terminal
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f8c521927f1 in __GI_abort () at abort.c:79
#2  0x00007f8c52b85957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f8c52b8bae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f8c52b8bb21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f8c52b8bd54 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f8c53fcc945 in nerf::NeRF_Model::GenerateBatch (this=this@entry=0x5619416f3990, pStream=<optimized out>, pTrainData=std::shared_ptr<nerf::NeRF_Dataset> (use count 4, weak count 0) = {...})
    at /home/zxq/MachineLearning/SLAM/RO-MAP/dependencies/Multi-Object-NeRF/Core/src/nerf_model.cu:1469
#7  0x00007f8c53fcd277 in nerf::NeRF_Model::Train_Step (this=0x5619416f3990, pTrainData=std::shared_ptr<nerf::NeRF_Dataset> (use count 4, weak count 0) = {...})
    at /home/zxq/MachineLearning/SLAM/RO-MAP/dependencies/Multi-Object-NeRF/Core/src/nerf_model.cu:1637
#8  0x00007f8c53fbe9ad in nerf::NeRF::TrainOffline (this=0x56194174e580, iterations=10) at /home/zxq/MachineLearning/SLAM/RO-MAP/dependencies/Multi-Object-NeRF/Core/src/nerf.cu:137
#9  0x00007f8c52bb66df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007f8c53c7e6db in start_thread (arg=0x7f8c3cfd3700) at pthread_create.c:463
#11 0x00007f8c5227361f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

因此，我猜测这可能和[tiny-cuda-nn](https://github.com/NVlabs/tiny-cuda-nn)有关。我们使用的tiny-cuda-nn版本是否相同？我在tiny-cuda-nn的issue中似乎也没寻找到合适的解决方案。

**Comment by XiaoHan-Git** [comment]
在repo上传代码后，我clone测试过，tiny-cuda-nn为自动递归下载的最新版本，即1.7。
从你给的调试信息来看，错误似乎是在nerf_model.cu中的GenerateBatch函数中访问了无效内存。但在我这边是没出现问题。
考虑到NeRF模型的训练是多线程的，请先尝试作如下修改以定位错误：
在上面仅构建1个NeRF模型的修改基础下，修改：
```c++
// ./RO-MAP/dependencies/Multi-Object-NeRF/Core/src/nerf_manager.cu 89行
//mvThreads.emplace_back(std::thread(&NeRF::TrainOffline,NeRFInstance,10)); 注释这行，增加下面这一行。不创建新线程
    NeRFInstance->TrainOffline(10); 

// ./RO-MAP/dependencies/Multi-Object-NeRF/Core/src/nerf_model.cu 1469行 
    CUDA_CHECK_THROW(cudaStreamSynchronize(cudaStreamPerThread));
    CUDA_CHECK_THROW(cudaStreamSynchronize(pStream));           //报错行，在上面加一行
```
请尝试上面修改，看是否仍然报错，报错位置是否变化。

**Comment by xxxxx391** [comment]
I have encountered the same problem, but according to your prompt, the problem has not been solved

**Comment by XiaoHan-Git** [comment]
Hi, @xxxxx391. Please check your Eigen version, it requires>=3.4.0. This allows Eigen to be used in CUDA __device__ functions.

**Comment by Geralt-of-winterfall** [comment]
> 在repo上传代码后，我clone测试过，tiny-cuda-nn为自动递归下载的最新版本，即1.7。 从你给的调试信息来看，错误似乎是在nerf_model.cu中的GenerateBatch函数中访问了无效内存。但在我这边是没出现问题。 考虑到NeRF模型的训练是多线程的，请先尝试作如下修改以定位错误： 在上面仅构建1个NeRF模型的修改基础下，修改：
> 
> ```c++
> // ./RO-MAP/dependencies/Multi-Object-NeRF/Core/src/nerf_manager.cu 89行
> //mvThreads.emplace_back(std::thread(&NeRF::TrainOffline,NeRFInstance,10)); 注释这行，增加下面这一行。不创建新线程
>     NeRFInstance->TrainOffline(10); 
> 
> // ./RO-MAP/dependencies/Multi-Object-NeRF/Core/src/nerf_model.cu 1469行 
>     CUDA_CHECK_THROW(cudaStreamSynchronize(cudaStreamPerThread));
>     CUDA_CHECK_THROW(cudaStreamSynchronize(pStream));           //报错行，在上面加一行
> ```
> 
> 请尝试上面修改，看是否仍然报错，报错位置是否变化。

按这里修改后，依旧报错，还是定位到同一个地方。
```shell
......Multi-Object NeRF Offline......
mNumGPU: 1
Detect 1 GPU ...
Load Images to GPU ...
Load Images to GPU completed...
GridEncoding:Nmin=16 b=1.38191 F=2 T=2^16 L=16
Model: 3--[HashGrid]-->32--[FullyFusedMLP(n_neurons=64|n_hidden_layers=1)]-->4(density=1,color=3)
 total_encoding_params=1908736 total_network_params=3072
allocate_time: 13
terminate called after throwing an instance of 'std::runtime_error'
  what():  /home/robert-kidder/桌面/RO-MAP/dependencies/Multi-Object-NeRF/Core/src/nerf_model.cu:1470 cudaStreamSynchronize(pStream) failed with error an illegal memory access was encountered
已放弃
```

**Comment by XiaoHan-Git** [comment]
@Geralt-of-winterfall , 你好，请先查看Eigen版本是否>=3.4.0，只有这之后的版本支持在CUDA device函数中使用Eigen。我在其他电脑上测试过，当Eigen低于3.4.0时会出现上述问题。

**Comment by Geralt-of-winterfall** [comment]
@XiaoHan-Git ，谢谢作者，确实是eigen的问题。切换版本后跑通了。
