### ISSUE TITLE
Usage of depth image for object SLAM 

### ISSUE THREAD

**Issue by Ssong0410** [XiaoHan-Git/RO-MAP#3]
Hello, your research was so impressive, and now I'm trying to run this code. 

I have a question about whether or not to use depth images. 

I read your paper and understood it as using only RGB images(video) and instance segmentation.

Then I'm wondering how to get a sparse point cloud that utilizes in lightweight object SLAM.

**Comment by XiaoHan-Git** [comment]
Hi, thanks for your interest.
RO-MAP uses only monocular input, and the sparse point cloud comes from ORB-SLAM2, which is generated by inter-frame triangulation during camera tracking. These point clouds are closely related to the feature points extracted on the image, and we use instance segmentation to associate them with "objects".
